services:
  postgres:
    image: postgres:17

    container_name: jes-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: jes
      POSTGRES_USER: jes
      POSTGRES_PASSWORD: jespassword

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
